In [42]:
# Первая часть - исследование

In [50]:
## Описание задачи 
### В данной работе предстоит моделировать отток клиентов телеком компании.
### Целевым признаком является столбец Church (Отток) в данных.
### Эта задача очень важна на практике и алгоритмы для ее решения используются в реальных 
### телеком компаниях, ведь если мы знаем, что клиент собирается уйти от нас, 
### то мы попытаться удержать его, предложив какие-то бонусы.

In [43]:
import kagglehub

path = kagglehub.competition_download('advanced-dls-spring-2021')
kagglehub.whoami()

Kaggle credentials successfully validated.

{'username': 'seradrug'}

In [44]:
## Импорты

In [65]:
import os 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [46]:
df = pd.read_csv(os.path.join(path, "train.csv"))
df.head()

,ClientPeriod,MonthlySpending,TotalSpent,Sex,IsSeniorCitizen,HasPartner,HasChild,HasPhoneService,HasMultiplePhoneNumbers,HasInternetService,HasOnlineSecurityService,HasOnlineBackup,HasDeviceProtection,HasTechSupportAccess,HasOnlineTV,HasMovieSubscription,HasContractPhone,IsBillingPaperless,PaymentMethod,Churn
0,55,19.50,1026.35,Male,0,Yes,Yes,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,0
1,72,25.85,1872.2,Male,0,Yes,No,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),0
2,1,75.90,75.9,Male,0,No,No,Yes,No,Fiber optic,No,No,No,Yes,No,No,Month-to-month,Yes,Electronic check,1
3,32,79.30,2570,Female,1,Yes,No,Yes,Yes,Fiber optic,No,No,Yes,No,No,No,Month-to-month,No,Mailed check,0
4,60,115.25,6758.45,Female,0,Yes,Yes,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),0

In [61]:
(df == " ").sum()

ClientPeriod                0
MonthlySpending             0
TotalSpent                  9
Sex                         0
IsSeniorCitizen             0
HasPartner                  0
HasChild                    0
HasPhoneService             0
HasMultiplePhoneNumbers     0
HasInternetService          0
HasOnlineSecurityService    0
HasOnlineBackup             0
HasDeviceProtection         0
HasTechSupportAccess        0
HasOnlineTV                 0
HasMovieSubscription        0
HasContractPhone            0
IsBillingPaperless          0
PaymentMethod               0
Churn                       0
dtype: int64

In [36]:
df.isna().sum() #пропусков нет вау

ClientPeriod                0
MonthlySpending             0
TotalSpent                  0
Sex                         0
IsSeniorCitizen             0
HasPartner                  0
HasChild                    0
HasPhoneService             0
HasMultiplePhoneNumbers     0
HasInternetService          0
HasOnlineSecurityService    0
HasOnlineBackup             0
HasDeviceProtection         0
HasTechSupportAccess        0
HasOnlineTV                 0
HasMovieSubscription        0
HasContractPhone            0
IsBillingPaperless          0
PaymentMethod               0
Churn                       0
dtype: int64

In [69]:
df = df.replace(" ", np.nan)

In [77]:
df[df.isna().any(axis=1)]

,ClientPeriod,MonthlySpending,TotalSpent,Sex,IsSeniorCitizen,HasPartner,HasChild,HasPhoneService,HasMultiplePhoneNumbers,HasInternetService,HasOnlineSecurityService,HasOnlineBackup,HasDeviceProtection,HasTechSupportAccess,HasOnlineTV,HasMovieSubscription,HasContractPhone,IsBillingPaperless,PaymentMethod,Churn
1048,0,25.75,NaN,Male,0,Yes,Yes,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,0
1707,0,73.35,NaN,Female,0,Yes,Yes,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,0
2543,0,19.70,NaN,Male,0,Yes,Yes,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,0
3078,0,80.85,NaN,Female,0,Yes,Yes,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,0
3697,0,20.00,NaN,Female,0,Yes,Yes,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,0
4002,0,61.90,NaN,Male,0,No,Yes,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),0
4326,0,25.35,NaN,Male,0,Yes,Yes,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,0
4551,0,52.55,NaN,Female,0,Yes,Yes,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),0
4598,0,56.05,NaN,Female,0,Yes,Yes,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),0

In [85]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5282 entries, 0 to 5281
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ClientPeriod              5282 non-null   int64
 1   MonthlySpending           5282 non-null   float64
 2   TotalSpent                5273 non-null   str
 3   Sex                       5282 non-null   str
 4   IsSeniorCitizen           5282 non-null   int64
 5   HasPartner                5282 non-null   str
 6   HasChild                  5282 non-null   str
 7   HasPhoneService           5282 non-null   str
 8   HasMultiplePhoneNumbers   5282 non-null   str
 9   HasInternetService        5282 non-null   str
 10  HasOnlineSecurityService  5282 non-null   str
 11  HasOnlineBackup           5282 non-null   str
 12  HasDeviceProtection       5282 non-null   str
 13  HasTechSupportAccess      5282 non-null   str
 14  HasOnlineTV               5282 non-null   str
 15  HasMovieSubscription      5282 non-null   str
 16  HasContractPhone          5282 non-null   str
 17  IsBillingPaperless        5282 non-null   str
 18  PaymentMethod             5282 non-null   str
 19  Churn                     5282 non-null   int64
dtypes: float64(1), int64(3), str(16)
memory usage: 1.3 MB

In [86]:
df["TotalSpent"] = df["TotalSpent"].astype(float)

In [90]:
df["TotalSpent"].dtype

dtype('float64')

In [100]:
filled_df = df.copy()
filled_df.head()

,ClientPeriod,MonthlySpending,TotalSpent,Sex,IsSeniorCitizen,HasPartner,HasChild,HasPhoneService,HasMultiplePhoneNumbers,HasInternetService,HasOnlineSecurityService,HasOnlineBackup,HasDeviceProtection,HasTechSupportAccess,HasOnlineTV,HasMovieSubscription,HasContractPhone,IsBillingPaperless,PaymentMethod,Churn
0,55,19.50,1026.35,Male,0,Yes,Yes,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,0
1,72,25.85,1872.20,Male,0,Yes,No,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),0
2,1,75.90,75.90,Male,0,No,No,Yes,No,Fiber optic,No,No,No,Yes,No,No,Month-to-month,Yes,Electronic check,1
3,32,79.30,2570.00,Female,1,Yes,No,Yes,Yes,Fiber optic,No,No,Yes,No,No,No,Month-to-month,No,Mailed check,0
4,60,115.25,6758.45,Female,0,Yes,Yes,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),0

In [101]:
## Заполняем все NaN на среднее значение в столбце TotalSpent при условии, что таргет = 0

In [102]:
filled_df["TotalSpent"] = filled_df["TotalSpent"].fillna(filled_df.loc[filled_df["Churn"] == 0, "TotalSpent"].mean())

In [116]:
filled_df["Sex"] = filled_df["Sex"].map({"Male": 1, "Female": 0})
yes_no_columns = [ 
    "HasPartner",
    "HasChild",
    "HasPhoneService",
    "IsBillingPaperless"
]
filled_df[yes_no_columns] = filled_df[yes_no_columns].replace({"Yes": 1, "No": 0})

no_internet_service_columns = [
    "HasOnlineSecurityService",
    "HasOnlineBackup",
    "HasDeviceProtection",
    "HasTechSupportAccess",
    "HasOnlineTV",
    "HasMovieSubscription"
]
filled_df[no_internet_service_columns] = filled_df[no_internet_service_columns].replace({
    "No internet service": 0, "No": 1, "Yes": 2
})

In [117]:
filled_df.head(20)

,ClientPeriod,MonthlySpending,TotalSpent,Sex,IsSeniorCitizen,HasPartner,HasChild,HasPhoneService,HasMultiplePhoneNumbers,HasInternetService,HasOnlineSecurityService,HasOnlineBackup,HasDeviceProtection,HasTechSupportAccess,HasOnlineTV,HasMovieSubscription,HasContractPhone,IsBillingPaperless,PaymentMethod,Churn
0,55,19.50,1026.35,NaN,0,1,1,1,No,No,0,0,0,0,0,0,One year,0,Mailed check,0
1,72,25.85,1872.20,NaN,0,1,0,1,Yes,No,0,0,0,0,0,0,Two year,0,Credit card (automatic),0
2,1,75.90,75.90,NaN,0,0,0,1,No,Fiber optic,1,1,1,2,1,1,Month-to-month,1,Electronic check,1
3,32,79.30,2570.00,NaN,1,1,0,1,Yes,Fiber optic,1,1,2,1,1,1,Month-to-month,0,Mailed check,0
4,60,115.25,6758.45,NaN,0,1,1,1,Yes,Fiber optic,2,2,2,2,2,2,Two year,0,Credit card (automatic),0
5,25,19.80,475.20,NaN,0,0,0,1,No,No,0,0,0,0,0,0,Two year,0,Credit card (automatic),0
6,27,90.15,2423.40,NaN,0,1,0,1,Yes,Fiber optic,1,1,2,1,1,2,Month-to-month,0,Bank transfer (automatic),0
7,1,45.70,45.70,NaN,0,0,0,1,No,DSL,1,1,1,1,1,1,Month-to-month,1,Mailed check,1
8,50,105.95,5341.80,NaN,0,1,1,1,Yes,Fiber optic,2,1,2,1,2,2,Month-to-month,0,Credit card (automatic),1
9,72,61.20,4390.25,NaN,0,0,0,0,No phone service,DSL,2,1,2,2,2,2,Two year,1,Credit card (automatic),0
10,16,78.75,1218.25,NaN,1,0,0,1,No,Fiber optic,1,1,1,1,1,2,Month-to-month,1,Electronic check,0
11,70,113.05,7869.05,NaN,0,1,1,1,Yes,Fiber optic,2,2,2,2,2,2,Two year,1,Credit card (automatic),0
12,69,99.50,6841.45,NaN,0,1,0,1,Yes,Fiber optic,1,1,2,1,2,2,One year,0,Bank transfer (automatic),0
13,26,38.85,1025.15,NaN,0,1,1,0,No phone service,DSL,2,2,1,2,1,1,Month-to-month,0,Credit card (automatic),0
14,38,102.60,4009.20,NaN,1,1,0,1,Yes,Fiber optic,1,2,2,1,2,2,Month-to-month,1,Electronic check,0
15,30,90.05,2627.20,NaN,1,1,0,1,Yes,Fiber optic,1,2,1,1,2,1,Month-to-month,1,Electronic check,0
16,52,53.75,2790.65,NaN,0,0,0,1,No,DSL,2,1,2,1,1,1,One year,0,Electronic check,0
17,71,90.30,6287.30,NaN,0,1,1,1,Yes,DSL,2,2,2,2,2,2,Two year,0,Credit card (automatic),0
18,59,19.85,1188.25,NaN,0,1,1,1,No,No,0,0,0,0,0,0,Two year,0,Mailed check,0
19,52,102.70,5138.10,NaN,0,1,0,1,Yes,Fiber optic,1,2,1,2,2,2,Month-to-month,1,Credit card (automatic),0

In [120]:
filled_df["PaymentMethod"].unique()

<ArrowStringArray>
[             'Mailed check',   'Credit card (automatic)',
          'Electronic check', 'Bank transfer (automatic)']
Length: 4, dtype: str